### PR TITLE
Community Garden plants sorted by health status

### PR DESCRIPTION
**Pull request by bjornwarmedal**

### CODE REVIEW

**Comment by bjornwarmedal** [comment]
Garden Gnome Society feature in the Community Garden! Always up to date :D 

This PR precludes the need for my other one. Decide which you like best.

**Comment by michael-lazar** [comment]
Hey ew0k!

I think I like this PR better, with the section headings for wilting, dead, etc. and all of the plants shown on the same page. When I do visit GGS, I like that I can visually skim through all of the dry, wilted, and dead plants without clicking through a bunch of links.

However, I don't want to change the main garden view because having them sorted by score and watching your plant climb the garden page is pretty much the only "reward" for playing the game.

What if we made this a separate view/template with a link from the current garden page kinda like this... 

```
# Astrobotany - Community Garden

=>/app 🚶 Go back

## Filters

=> /app/visit/health 🌡 Sort plants by health

## Plants

=> ...
```

There could even be an item in the store that you need to purchase to gain access to that page. Like a "soil testing kit" or something like that. Maybe that's taking it too far lol.

**Comment by bjornwarmedal** [comment]
I've thought about the idea of different filters, and I like it. I don't think an extra item should be bought to display it, because that'd prompt me to buy it and proxy that view to the Garden Gnome Society ;)

This opens up the possibility for more filtered views, too. Filter by water level, or plant stage, for example. Although I guess those would force a change in how and when flower status is refreshed. As I wrote on the Message Board the other day:

> @mozz on the Community Garden page the current stage is listed for each plant,
> but it "lags behind" since it's only recalculated when a plant is visited.
> - 🦄 ew0k, 2021-06-04

I'll scrap the other PR and re-implement this as a new view and we can take it from there :)

**Comment by michael-lazar** [comment]
> This opens up the possibility for more filtered views, too. Filter by water level, or plant stage, for example. Although I guess those would force a change in how and when flower status is refreshed. As I wrote on the Message Board the other day:

I've got a PR in the works to refresh all of the plants every hour via a cron job. Not perfect, but it should help with keeping the garden view up to date.

**Comment by bjornwarmedal** [comment]
The Garden Gnome Society walks through each plant four times a day, which means they're already updated at least that often (unless I have network issues) :)

**Comment by bjornwarmedal** [comment]
We can always add more sorted views later, but here's at least a first one :)

**Comment by michael-lazar** [comment]
Merged and deployed, thanks!!

**Pull request merged**
